---
- name: Unmount any currently mounted virtual disk
  dellemc.openmanage.idrac_virtual_media:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_username }}"
    idrac_password: "{{ idrac_password }}"
    command: "eject"
  tags:
    - eject

- name: Mount ISO as virtual media
  dellemc.openmanage.idrac_virtual_media:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_username }}"
    idrac_password: "{{ idrac_password }}"
    iso_url: "{{ iso_url }}"
    command: "insert"
  tags:
    - insert

- name: Set one-time boot to virtual media
  dellemc.openmanage.idrac_lifecycle_controller_jobs:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_username }}"
    idrac_password: "{{ idrac_password }}"
    boot_device: "VirtualMedia"
    reboot_job_type: "OneTime"
    state: "present"
  tags:
    - set_boot

- name: Power on the servers
  dellemc.openmanage.idrac_power_management:
    idrac_ip: "{{ idrac_ip }}"
    idrac_user: "{{ idrac_username }}"
    idrac_password: "{{ idrac_password }}"
    power_state: "on"
  tags:
    - power_on
